name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Setup environment
      run: |
        cp .env.template .env
        # Add test environment variables
        cat > .env << EOL
        PLAYLIST_URL=https://www.youtube.com/playlist?list=test
        NUM_GPUS=0
        NUM_CPUS=1
        BATCH_SIZE=1
        THREADS=1
        MODEL=llama3.2
        VERBOSE=false
        EOL
        
    - name: Run tests with pytest and coverage
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        python -m pytest
        
    - name: Generate Coverage Report
      run: |
        coverage report
        coverage html
        
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: |
          htmlcov/
          .coverage 